/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 19 21:11:42 GMT 2018
 */

package org.autotest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.autotest.StackAr;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StackAr_ESTest extends StackAr_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      boolean boolean0 = stackAr0.isEmpty();
      assertTrue(boolean0);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      stackAr0.push(object0);
      boolean boolean1 = stackAr0.isFull();
      assertFalse(boolean1);
      assertFalse(boolean1 == boolean0);
      
      int int0 = stackAr0.size();
      assertEquals(1, int0);
      
      Object object1 = stackAr0.get(0);
      assertSame(object1, object0);
      assertNotNull(object1);
      
      stackAr0.push(object0);
      assertSame(object0, object1);
      
      stackAr0.increaseCapacity(0);
      boolean boolean2 = stackAr0.isEmpty();
      assertFalse(boolean2);
      assertFalse(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      
      Object object2 = stackAr0.get(1);
      assertSame(object2, object1);
      assertSame(object2, object0);
      assertNotNull(object2);
      
      Object object3 = stackAr0.top();
      assertSame(object3, object0);
      assertSame(object3, object2);
      assertSame(object3, object1);
      assertNotNull(object3);
      
      String string0 = stackAr0.toString();
      assertNotNull(string0);
      
      stackAr0.increaseCapacity(0);
      boolean boolean3 = stackAr0.isEmpty();
      assertFalse(boolean3);
      assertFalse(boolean3 == boolean0);
      assertTrue(boolean3 == boolean2);
      assertTrue(boolean3 == boolean1);
      
      Object object4 = stackAr0.top();
      assertSame(object4, object2);
      assertSame(object4, object0);
      assertSame(object4, object3);
      assertSame(object4, object1);
      assertNotNull(object4);
      
      boolean boolean4 = stackAr0.isFull();
      assertFalse(boolean4);
      assertTrue(boolean4 == boolean3);
      assertTrue(boolean4 == boolean1);
      assertTrue(boolean4 == boolean2);
      assertFalse(boolean4 == boolean0);
      
      int int1 = stackAr0.size();
      assertEquals(2, int1);
      assertFalse(int1 == int0);
      
      boolean boolean5 = stackAr0.isEmpty();
      assertFalse(boolean5);
      assertFalse(boolean5 == boolean0);
      assertTrue(boolean5 == boolean2);
      assertTrue(boolean5 == boolean1);
      assertTrue(boolean5 == boolean3);
      assertTrue(boolean5 == boolean4);
      
      stackAr0.increaseCapacity(0);
      int int2 = stackAr0.size();
      assertEquals(2, int2);
      assertFalse(int2 == int0);
      assertTrue(int2 == int1);
      
      Object object5 = stackAr0.pop();
      assertSame(object5, object1);
      assertSame(object5, object3);
      assertSame(object5, object4);
      assertSame(object5, object0);
      assertSame(object5, object2);
      assertNotNull(object5);
      
      Object object6 = stackAr0.top();
      assertSame(object6, object1);
      assertSame(object6, object0);
      assertSame(object6, object3);
      assertSame(object6, object2);
      assertSame(object6, object4);
      assertSame(object6, object5);
      assertNotNull(object6);
      
      stackAr0.push(object6);
      assertSame(object6, object1);
      assertSame(object6, object0);
      assertSame(object6, object3);
      assertSame(object6, object2);
      assertSame(object6, object4);
      assertSame(object6, object5);
      
      boolean boolean6 = stackAr0.isFull();
      assertFalse(boolean6);
      assertTrue(boolean6 == boolean5);
      assertTrue(boolean6 == boolean3);
      assertTrue(boolean6 == boolean1);
      assertFalse(boolean6 == boolean0);
      assertTrue(boolean6 == boolean2);
      assertTrue(boolean6 == boolean4);
      
      Object object7 = stackAr0.get(0);
      assertSame(object7, object2);
      assertSame(object7, object0);
      assertSame(object7, object6);
      assertSame(object7, object3);
      assertSame(object7, object1);
      assertSame(object7, object4);
      assertSame(object7, object5);
      assertNotNull(object7);
      
      stackAr0.increaseCapacity(0);
      String string1 = stackAr0.toString();
      assertFalse(string1.equals((Object)string0));
      assertNotNull(string1);
      
      int int3 = stackAr0.size();
      assertEquals(2, int3);
      assertFalse(int3 == int0);
      assertTrue(int3 == int2);
      assertTrue(int3 == int1);
      
      int int4 = stackAr0.size();
      assertEquals(2, int4);
      assertFalse(int4 == int0);
      assertTrue(int4 == int3);
      assertTrue(int4 == int1);
      assertTrue(int4 == int2);
      
      boolean boolean7 = stackAr0.isFull();
      assertFalse(boolean7);
      assertTrue(boolean7 == boolean1);
      assertTrue(boolean7 == boolean4);
      assertFalse(boolean7 == boolean0);
      assertTrue(boolean7 == boolean2);
      assertTrue(boolean7 == boolean5);
      assertTrue(boolean7 == boolean3);
      assertTrue(boolean7 == boolean6);
      
      boolean boolean8 = stackAr0.isFull();
      assertFalse(boolean8);
      assertTrue(boolean8 == boolean5);
      assertFalse(boolean8 == boolean0);
      assertTrue(boolean8 == boolean2);
      assertTrue(boolean8 == boolean3);
      assertTrue(boolean8 == boolean4);
      assertTrue(boolean8 == boolean1);
      assertTrue(boolean8 == boolean6);
      assertTrue(boolean8 == boolean7);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StackAr stackAr0 = new StackAr(0);
      assertNotNull(stackAr0);
      
      stackAr0.increaseCapacity(6148);
      // Undeclared exception!
      stackAr0.push((Object) null);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      boolean boolean0 = stackAr0.isEmpty();
      assertTrue(boolean0);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      stackAr0.push(object0);
      boolean boolean1 = stackAr0.isFull();
      assertFalse(boolean1);
      assertFalse(boolean1 == boolean0);
      
      int int0 = stackAr0.size();
      assertEquals(1, int0);
      
      Object object1 = stackAr0.top();
      assertSame(object1, object0);
      assertNotNull(object1);
      
      String string0 = stackAr0.toString();
      assertNotNull(string0);
      
      stackAr0.push(object0);
      assertSame(object0, object1);
      
      Object object2 = stackAr0.pop();
      assertSame(object2, object0);
      assertSame(object2, object1);
      assertNotNull(object2);
      
      stackAr0.increaseCapacity(0);
      boolean boolean2 = stackAr0.isFull();
      assertFalse(boolean2);
      assertTrue(boolean2 == boolean1);
      assertFalse(boolean2 == boolean0);
      
      Object object3 = stackAr0.get(1);
      assertNull(object3);
      
      Object object4 = stackAr0.top();
      assertSame(object4, object0);
      assertSame(object4, object1);
      assertSame(object4, object2);
      assertNotNull(object4);
      
      String string1 = stackAr0.toString();
      assertFalse(string1.equals((Object)string0));
      assertNotNull(string1);
      
      stackAr0.increaseCapacity(0);
      boolean boolean3 = stackAr0.isEmpty();
      assertFalse(boolean3);
      assertFalse(boolean3 == boolean0);
      assertTrue(boolean3 == boolean1);
      assertTrue(boolean3 == boolean2);
      
      Object object5 = stackAr0.top();
      assertSame(object5, object0);
      assertSame(object5, object2);
      assertSame(object5, object4);
      assertSame(object5, object1);
      assertNotNull(object5);
      
      boolean boolean4 = stackAr0.isFull();
      assertFalse(boolean4);
      assertTrue(boolean4 == boolean1);
      assertTrue(boolean4 == boolean3);
      assertFalse(boolean4 == boolean0);
      assertTrue(boolean4 == boolean2);
      
      int int1 = stackAr0.size();
      assertEquals(1, int1);
      assertTrue(int1 == int0);
      
      boolean boolean5 = stackAr0.isEmpty();
      assertFalse(boolean5);
      assertTrue(boolean5 == boolean3);
      assertTrue(boolean5 == boolean1);
      assertTrue(boolean5 == boolean4);
      assertFalse(boolean5 == boolean0);
      assertTrue(boolean5 == boolean2);
      
      stackAr0.increaseCapacity(1);
      int int2 = stackAr0.size();
      assertEquals(1, int2);
      assertTrue(int2 == int0);
      assertTrue(int2 == int1);
      
      Object object6 = stackAr0.pop();
      assertSame(object6, object1);
      assertSame(object6, object5);
      assertSame(object6, object0);
      assertSame(object6, object2);
      assertSame(object6, object4);
      assertNotNull(object6);
      
      try { 
        stackAr0.top();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      int int0 = (-2477);
      // Undeclared exception!
      try { 
        stackAr0.increaseCapacity((-2477));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      int int0 = stackAr0.size();
      assertEquals(0, int0);
      
      // Undeclared exception!
      try { 
        stackAr0.increaseCapacity((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      stackAr0.increaseCapacity(1);
      stackAr0.increaseCapacity(1901);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StackAr stackAr0 = new StackAr(0);
      assertNotNull(stackAr0);
      
      stackAr0.increaseCapacity(0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      Object object0 = stackAr0.get(0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StackAr stackAr0 = new StackAr(0);
      assertNotNull(stackAr0);
      
      try { 
        stackAr0.pop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = (-1);
      StackAr stackAr0 = null;
      try {
        stackAr0 = new StackAr((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      try { 
        stackAr0.pop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StackAr stackAr0 = null;
      try {
        stackAr0 = new StackAr((-3193));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StackAr stackAr0 = new StackAr(1598);
      assertNotNull(stackAr0);
      
      stackAr0.push((Object) null);
      boolean boolean0 = stackAr0.isEmpty();
      assertFalse(boolean0);
      
      boolean boolean1 = stackAr0.isEmpty();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      
      Object object0 = stackAr0.pop();
      assertNull(object0);
      
      stackAr0.push((Object) null);
      boolean boolean2 = stackAr0.isFull();
      assertFalse(boolean2);
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      
      try { 
        stackAr0.get(1598);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      boolean boolean0 = stackAr0.isFull();
      assertFalse(boolean0);
      
      int int0 = stackAr0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StackAr stackAr0 = new StackAr(0);
      assertNotNull(stackAr0);
      
      String string0 = stackAr0.toString();
      assertEquals("[,]", string0);
      assertNotNull(string0);
      
      String string1 = stackAr0.toString();
      assertEquals("[,]", string1);
      assertTrue(string1.equals((Object)string0));
      assertNotNull(string1);
      
      try { 
        stackAr0.push("[,]");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      boolean boolean0 = stackAr0.isEmpty();
      assertTrue(boolean0);
      
      stackAr0.push("");
      Object object0 = stackAr0.get(0);
      assertEquals("", object0);
      assertNotNull(object0);
      
      boolean boolean1 = stackAr0.isEmpty();
      assertFalse(boolean1);
      assertFalse(boolean1 == boolean0);
      
      Object object1 = stackAr0.top();
      assertEquals("", object1);
      assertNotNull(object1);
      
      stackAr0.push("");
      try { 
        stackAr0.get(3129);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StackAr stackAr0 = new StackAr(0);
      assertNotNull(stackAr0);
      
      boolean boolean0 = stackAr0.isFull();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      stackAr0.push((Object) null);
      Object object0 = stackAr0.top();
      assertNull(object0);
      
      String string0 = stackAr0.toString();
      assertEquals("[null]", string0);
      assertNotNull(string0);
      
      String string1 = stackAr0.toString();
      assertEquals("[null]", string1);
      assertTrue(string1.equals((Object)string0));
      assertNotNull(string1);
      
      String string2 = stackAr0.toString();
      assertEquals("[null]", string2);
      assertTrue(string2.equals((Object)string0));
      assertTrue(string2.equals((Object)string1));
      assertNotNull(string2);
      
      Object object1 = stackAr0.top();
      assertNull(object1);
      
      int int0 = stackAr0.size();
      assertEquals(1, int0);
      
      Object object2 = stackAr0.top();
      assertNull(object2);
      
      Object object3 = stackAr0.top();
      assertNull(object3);
      
      boolean boolean0 = stackAr0.isFull();
      assertFalse(boolean0);
      
      int int1 = stackAr0.size();
      assertEquals(1, int1);
      assertTrue(int1 == int0);
      
      String string3 = stackAr0.toString();
      assertEquals("[null]", string3);
      assertTrue(string3.equals((Object)string0));
      assertTrue(string3.equals((Object)string2));
      assertTrue(string3.equals((Object)string1));
      assertNotNull(string3);
      
      boolean boolean1 = stackAr0.isFull();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      
      Object object4 = stackAr0.top();
      assertNull(object4);
      
      int int2 = stackAr0.size();
      assertEquals(1, int2);
      assertTrue(int2 == int0);
      assertTrue(int2 == int1);
      
      Object object5 = stackAr0.get(0);
      assertNull(object5);
      
      boolean boolean2 = stackAr0.isEmpty();
      assertFalse(boolean2);
      assertTrue(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      
      boolean boolean3 = stackAr0.isFull();
      assertFalse(boolean3);
      assertTrue(boolean3 == boolean2);
      assertTrue(boolean3 == boolean1);
      assertTrue(boolean3 == boolean0);
      
      stackAr0.push((Object) null);
      Object object6 = stackAr0.get(1);
      assertNull(object6);
      
      stackAr0.push((Object) null);
      boolean boolean4 = stackAr0.isFull();
      assertFalse(boolean4);
      assertTrue(boolean4 == boolean0);
      assertTrue(boolean4 == boolean3);
      assertTrue(boolean4 == boolean2);
      assertTrue(boolean4 == boolean1);
      
      int int3 = stackAr0.size();
      assertEquals(3, int3);
      assertFalse(int3 == int1);
      assertFalse(int3 == int0);
      assertFalse(int3 == int2);
      
      try { 
        stackAr0.get(1066);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      stackAr0.push("29,?|7");
      Object object0 = stackAr0.get(0);
      assertEquals("29,?|7", object0);
      assertNotNull(object0);
      
      int int0 = 0;
      Object object1 = stackAr0.get(0);
      assertEquals("29,?|7", object1);
      assertNotNull(object1);
      
      int int1 = 0;
      String string0 = stackAr0.toString();
      assertEquals("[29,?|7]", string0);
      assertFalse(string0.equals((Object)object1));
      assertFalse(string0.equals((Object)object0));
      assertNotNull(string0);
      
      String string1 = stackAr0.toString();
      assertEquals("[29,?|7]", string1);
      assertTrue(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)object0));
      assertFalse(string1.equals((Object)object1));
      assertNotNull(string1);
      
      stackAr0.push("[29,?|7]");
      String string2 = stackAr0.toString();
      assertEquals("[29,?|7,[29,?|7]]", string2);
      assertFalse(string2.equals((Object)string0));
      assertFalse(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)object1));
      assertFalse(string2.equals((Object)object0));
      assertNotNull(string2);
      
      Object object2 = stackAr0.get(0);
      assertEquals("29,?|7", object2);
      assertFalse(object2.equals((Object)string1));
      assertFalse(object2.equals((Object)string0));
      assertFalse(object2.equals((Object)string2));
      assertNotNull(object2);
      
      Object object3 = stackAr0.pop();
      assertEquals("[29,?|7]", object3);
      assertFalse(object3.equals((Object)object2));
      assertTrue(object3.equals((Object)string0));
      assertFalse(object3.equals((Object)string2));
      assertFalse(object3.equals((Object)object1));
      assertFalse(object3.equals((Object)object0));
      assertTrue(object3.equals((Object)string1));
      assertNotNull(object3);
      
      String string3 = stackAr0.toString();
      assertEquals("[29,?|7]", string3);
      assertTrue(string3.equals((Object)string1));
      assertTrue(string3.equals((Object)object3));
      assertFalse(string3.equals((Object)string2));
      assertFalse(string3.equals((Object)object0));
      assertFalse(string3.equals((Object)object2));
      assertTrue(string3.equals((Object)string0));
      assertFalse(string3.equals((Object)object1));
      assertNotNull(string3);
      
      Object object4 = stackAr0.top();
      assertEquals("29,?|7", object4);
      assertFalse(object4.equals((Object)string3));
      assertFalse(object4.equals((Object)string0));
      assertFalse(object4.equals((Object)object3));
      assertFalse(object4.equals((Object)string1));
      assertFalse(object4.equals((Object)string2));
      assertNotNull(object4);
      
      Object object5 = stackAr0.pop();
      assertEquals("29,?|7", object5);
      assertFalse(object5.equals((Object)string1));
      assertFalse(object5.equals((Object)string2));
      assertFalse(object5.equals((Object)string3));
      assertFalse(object5.equals((Object)object3));
      assertFalse(object5.equals((Object)string0));
      assertNotNull(object5);
      
      stackAr0.push("29,?|7");
      stackAr0.push((Object) null);
      Object object6 = stackAr0.pop();
      assertNull(object6);
      
      Object object7 = stackAr0.pop();
      assertEquals("29,?|7", object7);
      assertTrue(object7.equals((Object)object1));
      assertFalse(object7.equals((Object)string1));
      assertTrue(object7.equals((Object)object2));
      assertFalse(object7.equals((Object)string0));
      assertFalse(object7.equals((Object)object3));
      assertFalse(object7.equals((Object)string3));
      assertTrue(object7.equals((Object)object5));
      assertTrue(object7.equals((Object)object0));
      assertFalse(object7.equals((Object)string2));
      assertTrue(object7.equals((Object)object4));
      assertNotNull(object7);
      
      String string4 = stackAr0.toString();
      assertEquals("[,]", string4);
      assertFalse(string4.equals((Object)string0));
      assertFalse(string4.equals((Object)string2));
      assertFalse(string4.equals((Object)object0));
      assertFalse(string4.equals((Object)object1));
      assertFalse(string4.equals((Object)string3));
      assertFalse(string4.equals((Object)object5));
      assertFalse(string4.equals((Object)object4));
      assertFalse(string4.equals((Object)object2));
      assertFalse(string4.equals((Object)object7));
      assertFalse(string4.equals((Object)string1));
      assertFalse(string4.equals((Object)object3));
      assertNotNull(string4);
      
      try { 
        stackAr0.top();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      try { 
        stackAr0.top();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      assertNotNull(stackAr0);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      stackAr0.push(object0);
      Object object1 = stackAr0.get(0);
      assertSame(object1, object0);
      assertNotNull(object1);
      
      int int0 = stackAr0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      StackAr stackAr0 = new StackAr(1);
      assertNotNull(stackAr0);
      
      String string0 = stackAr0.toString();
      assertEquals("[,]", string0);
      assertNotNull(string0);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      stackAr0.push(object0);
      boolean boolean0 = stackAr0.isEmpty();
      assertFalse(boolean0);
      
      Object object1 = stackAr0.pop();
      assertSame(object1, object0);
      assertNotNull(object1);
      
      boolean boolean1 = stackAr0.isFull();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      
      stackAr0.increaseCapacity(548);
      stackAr0.push(object1);
      assertSame(object1, object0);
      
      boolean boolean2 = stackAr0.isFull();
      assertFalse(boolean2);
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      
      Object object2 = stackAr0.pop();
      assertSame(object2, object0);
      assertSame(object2, object1);
      assertNotNull(object2);
      
      stackAr0.push(object0);
      assertSame(object0, object2);
      assertSame(object0, object1);
      
      String string1 = stackAr0.toString();
      assertFalse(string1.equals((Object)string0));
      assertNotNull(string1);
      
      stackAr0.increaseCapacity(1);
      // Undeclared exception!
      stackAr0.push((Object) null);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int int0 = 1;
      StackAr stackAr0 = new StackAr(1);
      stackAr0.toString();
      Object object0 = new Object();
      stackAr0.isEmpty();
      stackAr0.push(object0);
      stackAr0.isEmpty();
      stackAr0.pop();
      try { 
        stackAr0.get(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      StackAr stackAr0 = null;
      try {
        stackAr0 = new StackAr((-5075));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      StackAr stackAr0 = new StackAr(0);
      Object object0 = new Object();
      try { 
        stackAr0.push(object0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      stackAr0.isEmpty();
      Object object0 = new Object();
      stackAr0.push(object0);
      stackAr0.isEmpty();
      stackAr0.get(0);
      stackAr0.toString();
      stackAr0.push(object0);
      stackAr0.pop();
      // Undeclared exception!
      try { 
        stackAr0.increaseCapacity((-127));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      stackAr0.push("org.autotest.StackAr");
      Object object0 = new Object();
      stackAr0.push(object0);
      Object object1 = stackAr0.pop();
      assertNotNull(object1);
      
      stackAr0.push(object1);
      int int0 = stackAr0.size();
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      stackAr0.push("29,?|7");
      int int0 = 0;
      stackAr0.pop();
      stackAr0.get(0);
      stackAr0.toString();
      try { 
        stackAr0.top();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      String string0 = null;
      stackAr0.push((Object) null);
      stackAr0.top();
      stackAr0.push((Object) null);
      stackAr0.toString();
      int int0 = (-25);
      try { 
        stackAr0.get((-25));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.autotest.StackAr", e);
      }
  }


  // Nuevo test para coverage
  @Test(timeout = 40000000)
  public void test29()  throws Throwable {
        StackAr stackAr0 = new StackAr(1);
        stackAr0.increaseCapacity(2);
        String string0 = null;
        stackAr0.push((Object) 1);
        stackAr0.push((Object) 2);
        int a = (int) stackAr0.pop();
        int b = (int) stackAr0.pop();

        assertEquals(a, 2);
        assertEquals(b, 1);
  }
}
